db_host: "120.27.217.130:3306"
db_username: root
db_password: Wyun4test
db_name: gateway

oauth_host: "http://oauth-center/oauth/user/getUser?access_token="
#oauth_host: "127.0.0.1:8082"

"max_conns": 512
"max_conn_duration": 10
"max_idle_conn_duration": 10
"read_buffer_size": 4096
"write_buffer_size": 4096
"read_timeout": 30
"write_timeout": 30
"max_response_body_size": 104857600
